In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [6]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
df.shape

(10000, 11)

In [8]:
df.duplicated().sum()

0

In [9]:
df.Exited.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [10]:
df.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [11]:
df.Gender.value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [12]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [13]:
df['Gender'].map({"Female":0,"Male":1})

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64

In [14]:
df["Gender"] = df['Gender'].map({"Female":0,"Male":1})
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [15]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [16]:
df['Geography'] = df['Geography'].map({'France':0,'Spain':1,'Germany':2})
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          1       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          1       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [17]:
X = df.drop(columns = ['Exited'])

In [18]:
y = df['Exited']

In [19]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [20]:
scaler = StandardScaler()

In [21]:
X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test)

In [22]:
X_train_scaled

array([[-0.23082038,  1.49644863,  0.91509065, ..., -1.55337352,
         0.97725852,  0.42739449],
       [-0.25150912, -0.90651986, -1.09278791, ..., -1.55337352,
        -1.02327069, -1.02548708],
       [-0.3963303 ,  1.49644863, -1.09278791, ...,  0.64376017,
         0.97725852, -0.94479772],
       ...,
       [ 0.22433188, -0.90651986, -1.09278791, ...,  0.64376017,
         0.97725852, -0.14096853],
       [ 0.13123255, -0.90651986, -1.09278791, ...,  0.64376017,
         0.97725852,  0.01781218],
       [ 1.1656695 ,  1.49644863,  0.91509065, ...,  0.64376017,
        -1.02327069, -1.15822478]])

In [23]:
X_test_scaled

array([[-1.03768121, -0.90651986,  0.91509065, ...,  0.64376017,
         0.97725852, -0.05360571],
       [ 0.30708683, -0.90651986,  0.91509065, ...,  0.64376017,
        -1.02327069, -0.58392685],
       [-1.23422423, -0.90651986, -1.09278791, ..., -1.55337352,
         0.97725852, -0.16685331],
       ...,
       [-0.86182692,  0.29496438,  0.91509065, ..., -1.55337352,
         0.97725852,  1.0669965 ],
       [-0.30323097,  1.49644863, -1.09278791, ...,  0.64376017,
         0.97725852,  1.13101314],
       [ 0.04847759,  1.49644863,  0.91509065, ...,  0.64376017,
         0.97725852, -0.88790165]])

In [24]:
model = Sequential()
model.add(Dense(11, activation='sigmoid', input_dim = X_train_scaled.shape[1]))
model.add(Dense(11,activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 11)                121       
                                                                 
 dense_1 (Dense)             (None, 11)                132       
                                                                 
 dense_2 (Dense)             (None, 1)                 12        
                                                                 
Total params: 265
Trainable params: 265
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [27]:
model.fit(X_train,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.2)

Epoch 1/100
128/128 [==============================] - 2s 7ms/step - loss: 0.6092 - accuracy: 0.6880 - val_loss: 0.5174 - val_accuracy: 0.7975
Epoch 2/100
128/128 [==============================] - 0s 3ms/step - loss: 0.5063 - accuracy: 0.7972 - val_loss: 0.5013 - val_accuracy: 0.7975
Epoch 3/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5013 - accuracy: 0.7972 - val_loss: 0.5002 - val_accuracy: 0.7975
Epoch 4/100
128/128 [==============================] - 0s 3ms/step - loss: 0.5004 - accuracy: 0.7972 - val_loss: 0.4993 - val_accuracy: 0.7975
Epoch 5/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4999 - accuracy: 0.7972 - val_loss: 0.4988 - val_accuracy: 0.7975
Epoch 6/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4995 - accuracy: 0.7972 - val_loss: 0.4986 - val_accuracy: 0.7975
Epoch 7/100
128/128 [==============================] - 0s 4ms/step - loss: 0.4990 - accuracy: 0.7972 - val_loss: 0.4980 - val_accuracy: 0.7975

Epoch 58/100
128/128 [==============================] - 0s 4ms/step - loss: 0.4971 - accuracy: 0.7972 - val_loss: 0.4960 - val_accuracy: 0.7975
Epoch 59/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4971 - accuracy: 0.7972 - val_loss: 0.4962 - val_accuracy: 0.7975
Epoch 60/100
128/128 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7972 - val_loss: 0.4960 - val_accuracy: 0.7975
Epoch 61/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4972 - accuracy: 0.7972 - val_loss: 0.4960 - val_accuracy: 0.7975
Epoch 62/100
128/128 [==============================] - 0s 4ms/step - loss: 0.4971 - accuracy: 0.7972 - val_loss: 0.4960 - val_accuracy: 0.7975
Epoch 63/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4973 - accuracy: 0.7972 - val_loss: 0.4960 - val_accuracy: 0.7975
Epoch 64/100
128/128 [==============================] - 0s 4ms/step - loss: 0.4971 - accuracy: 0.7972 - val_loss: 0.4962 - val_accuracy:

In [28]:
model.layers[0].get_weights()

[array([[ 0.02555358,  0.5223477 ,  0.50994295,  0.46569118,  0.2176956 ,
         -0.50695986, -0.23738854, -0.17667557, -0.12653056, -0.00524282,
         -0.04711804],
        [ 0.24494432,  0.16088921, -0.41152674, -0.49554393,  0.46627694,
          0.43188238,  0.5804104 , -0.36063135,  0.41889954,  0.03527796,
         -0.33666104],
        [ 0.07025217, -0.26381013,  0.47786957, -0.28947452, -0.37321493,
          0.40040532, -0.11315235, -0.32731915,  0.11140519,  0.01957785,
          0.44275284],
        [ 0.25057843, -0.05392895, -0.5119044 , -0.37051776, -0.29612184,
          0.38441086,  0.3070428 , -0.03611337,  0.10060352, -0.40604097,
          0.5331679 ],
        [ 0.2668306 , -0.0439447 , -0.2302019 , -0.00820481,  0.35263819,
         -0.20891741, -0.20018096,  0.20800625, -0.2220205 ,  0.23367192,
          0.31711757],
        [-0.33995628, -0.13450825, -0.46892726,  0.03257411,  0.45426327,
          0.1067214 ,  0.17092057,  0.26802045, -0.34593117,  0.4846814

In [29]:
model.layers[1].get_weights()

[array([[ 0.21014403,  0.02517424, -0.35971105,  0.37868   , -0.07265688,
          0.02243744, -0.33749503,  0.2806151 , -0.71430415, -0.10598106,
         -0.04594027],
        [-0.17445338, -0.04989932, -0.113552  , -0.10517589, -0.7488204 ,
         -0.11080742, -0.14870314,  0.63131845, -0.15721193,  0.121282  ,
         -0.67824066],
        [ 0.39805165, -0.9470587 , -0.43839496,  0.20049293, -0.24653746,
          0.7527062 ,  0.5241427 ,  0.2951743 ,  0.62884647, -0.41216752,
          0.15290664],
        [ 0.07634129,  0.3763831 , -0.67133564,  0.5232883 , -0.67361397,
          0.16395372,  0.3404529 , -0.31277096,  0.27236682,  0.01978061,
         -0.59433913],
        [ 0.06156113, -0.30769342, -0.2652259 ,  0.5434373 , -0.06768329,
          0.28086847, -0.22302507,  0.07140102,  0.20700279,  0.01552582,
         -0.545824  ],
        [ 0.48691508, -0.05429148, -0.5354369 ,  0.14447446, -0.09485687,
          0.16634716, -0.16959797,  0.2897724 ,  0.47398904, -0.6654444

In [30]:
model.layers[2].get_weights()

[array([[-0.7466835 ],
        [ 0.5129517 ],
        [ 0.24114491],
        [-0.19559242],
        [ 0.15638407],
        [-0.15263832],
        [-0.79462516],
        [-0.28663066],
        [-0.4890181 ],
        [ 0.34118792],
        [ 0.14370081]], dtype=float32),
 array([-0.13641047], dtype=float32)]

In [31]:
y_log = model.predict(X_test_scaled)
y_log

63/63 [==============================] - 0s 2ms/step


array([[0.20463242],
       [0.2009773 ],
       [0.20730238],
       ...,
       [0.1805349 ],
       [0.21427172],
       [0.23725154]], dtype=float32)

In [32]:
y_pred = np.where(y_log>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [33]:
accuracy_score(y_test,y_pred)

0.7925